In [2]:
import numpy as np

np.arange(2, 50, 3) 

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [6]:
import numpy

list1=[]
list2=[]

for i in range (5):
    a=int(input("Enter elements for list1 :"))
    list1.append(a)    
print (list1)
arr1 = numpy.array(list1)
print (arr1)

for j in range (5):
    b=int(input("Enter elements for list2 :"))
    list2.append(b)    
print (list2)
arr2 = numpy.array(list2)
print (arr2)

print(numpy.concatenate((arr1, arr2)))

arr1.sort()
print('Sorted Array1 : ', arr1)

arr2.sort()
print('Sorted Array2 : ', arr2)

Enter elements for list1 :23
Enter elements for list1 :34
Enter elements for list1 :78
Enter elements for list1 :65
Enter elements for list1 :1
[23, 34, 78, 65, 1]
[23 34 78 65  1]
Enter elements for list2 :27
Enter elements for list2 :98
Enter elements for list2 :67
Enter elements for list2 :12
Enter elements for list2 :3
[27, 98, 67, 12, 3]
[27 98 67 12  3]
[23 34 78 65  1 27 98 67 12  3]
Sorted Array1 :  [ 1 23 34 65 78]
Sorted Array2 :  [ 3 12 27 67 98]


In [9]:
import numpy as np

a_1d = np.arange(3)
print(a_1d)

a_2d = np.arange(12).reshape((3, 4))
print(a_2d)

a_3d = np.arange(24).reshape((2, 3, 4))
print(a_3d)

#shape

print(a_1d.shape)
print(a_2d.shape)
print(a_3d.shape)

#size

print(a_1d.size)
print(a_2d.size)
print(a_3d.size)

[0 1 2]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(3,)
(3, 4)
(2, 3, 4)
3
12
24


In [13]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr)
# Convert 1D array to a 2D numpy array of 2 rows and 3 columns
arr_2d = np.reshape(arr, (2, 5))
print(arr_2d)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [20]:
import numpy as np

a = np.array([[1,5,9], [2,6,10]])
b = np.array([[3,7,11], [4,8,12]])

print(np.concatenate((a,b), axis=0))
print(np.concatenate((a, b), axis=1))

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
[[ 1  5  9  3  7 11]
 [ 2  6 10  4  8 12]]


In [24]:
import numpy as np

#1-d array
a = np.array([[1, 1], [2, 3]])
print(np.unique(a))

#2-d array
a = np.array([[1, 0, 0], [1, 0, 0], [2, 3, 4]])
print(np.unique(a, axis=0))


[1 2 3]
[[1 0 0]
 [2 3 4]]
